/*
 * This file is generated by jOOQ.
*/
package com.tutorial.rest.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles implements Serializable {

    private static final long serialVersionUID = -1560998282;

    private Long   roleId;
    private String roleName;
    private Long   userId;

    public Roles() {}

    public Roles(Roles value) {
        this.roleId = value.roleId;
        this.roleName = value.roleName;
        this.userId = value.userId;
    }

    public Roles(
        Long   roleId,
        String roleName,
        Long   userId
    ) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.userId = userId;
    }

    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Roles (");

        sb.append(roleId);
        sb.append(", ").append(roleName);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
