/*
 * This file is generated by jOOQ.
*/
package com.tutorial.rest.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = -16758412;

    private Long   userId;
    private String userName;
    private String pass;
    private String email;
    private Short  enabled;

    public Users() {}

    public Users(Users value) {
        this.userId = value.userId;
        this.userName = value.userName;
        this.pass = value.pass;
        this.email = value.email;
        this.enabled = value.enabled;
    }

    public Users(
        Long   userId,
        String userName,
        String pass,
        String email,
        Short  enabled
    ) {
        this.userId = userId;
        this.userName = userName;
        this.pass = pass;
        this.email = email;
        this.enabled = enabled;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPass() {
        return this.pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Short getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Short enabled) {
        this.enabled = enabled;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(pass);
        sb.append(", ").append(email);
        sb.append(", ").append(enabled);

        sb.append(")");
        return sb.toString();
    }
}
