/*
 * This file is generated by jOOQ.
*/
package com.tutorial.rest.jooq.tables.daos;


import com.tutorial.rest.jooq.tables.Roles;
import com.tutorial.rest.jooq.tables.records.RolesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesDao extends DAOImpl<RolesRecord, com.tutorial.rest.jooq.tables.pojos.Roles, Record2<Long, Long>> {

    /**
     * Create a new RolesDao without any configuration
     */
    public RolesDao() {
        super(Roles.ROLES, com.tutorial.rest.jooq.tables.pojos.Roles.class);
    }

    /**
     * Create a new RolesDao with an attached configuration
     */
    public RolesDao(Configuration configuration) {
        super(Roles.ROLES, com.tutorial.rest.jooq.tables.pojos.Roles.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, Long> getId(com.tutorial.rest.jooq.tables.pojos.Roles object) {
        return compositeKeyRecord(object.getRoleId(), object.getUserId());
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.tutorial.rest.jooq.tables.pojos.Roles> fetchByRoleId(Long... values) {
        return fetch(Roles.ROLES.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>role_name IN (values)</code>
     */
    public List<com.tutorial.rest.jooq.tables.pojos.Roles> fetchByRoleName(String... values) {
        return fetch(Roles.ROLES.ROLE_NAME, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.tutorial.rest.jooq.tables.pojos.Roles> fetchByUserId(Long... values) {
        return fetch(Roles.ROLES.USER_ID, values);
    }
}
