/*
 * This file is generated by jOOQ.
*/
package com.tutorial.rest.jooq;


import com.tutorial.rest.jooq.tables.Roles;
import com.tutorial.rest.jooq.tables.SchemaVersion;
import com.tutorial.rest.jooq.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = com.tutorial.rest.jooq.tables.Roles.ROLES;

    /**
     * The table <code>public.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = com.tutorial.rest.jooq.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = com.tutorial.rest.jooq.tables.Users.USERS;
}
