management:
  security:
    enabled: true
    roles: ACTRADMIN

security:
  user:
    name: config
    password: ${CONFIG_SERVICE_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/